os: osx
osx_image: xcode8

sudo: required
branches:
  only:
  - release
  - dev
git:
  submodules: false
language: node_js
node_js: "8"
cache:
  directories:
  - node_modules
  - $HOME/.electron
before_install:
- if [ "$TRAVIS_BRANCH" = "release" ]; then openssl aes-256-cbc -K $encrypted_fec05b564c85_key -iv $encrypted_fec05b564c85_iv
  -in id_rsa.enc -out packaging/id_rsa -d; fi
script:
- if [ "$TRAVIS_BRANCH" = "release" ]; then
    npm run lint && npm run dist:mac;
  else
    npm run lint;
  fi
